# App
APP_NAME: Infra Api
APP_VERSION: 0.1
APP_URL: "0.0.0.0"
APP_PORT: 8000

# API
API_TIMEOUT: 15
ENABLE_DEBUG: true

# Blockchain
NODE_URL: https://mainnet.infura.io/v3/5bfa6b51715c4ee1a18c14364bfc8e13
